from os import environ

SQLALCHEMY_DATABASE_URI = environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')

AUTH0_DOMAIN = environ.get('AUTH0_DOMAIN')
API_IDENTIFIER = environ.get('API_IDENTIFIER')
ALGORITHMS = ["RS256"]