openapi: 3.0.0
info:
  title: MindTracker API
  description: MindTracker REST service
  version: 0.1.0
servers:
  - url: /api/v1
paths:
  /records:
    get:
      summary: Returns a list of records. Each record is a mind representation
      responses:
        "200":
          description: A JSON array of mind records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Record"
    post:
      summary: Creates a new record of mind representation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Record"
      responses:
        "200":
          description: A newly created record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Record"

components:
  schemas:
    Record:
      properties:
        id:
          type: integer
        mood:
          type: integer
        energy:
          type: integer
        date:
          type: string
      required:
        - mood
        - energy
